# Generated by Django 3.0.3 on 2020-11-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_manager', '0001_initial'),
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAdTemplate',
            fields=[
                ('adtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads_manager.AdTemplate')),
                ('title', models.CharField(max_length=40)),
                ('title2', models.CharField(blank=True, max_length=40)),
                ('text', models.CharField(max_length=128)),
                ('href', models.URLField(max_length=1024)),
            ],
            bases=('ads_manager.adtemplate',),
        ),
    ]
