# Generated by Django 3.0.3 on 2020-12-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0003_auto_20201128_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='directstats',
            name='shows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
