# Generated by Django 3.0.3 on 2020-06-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_xml_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='modtime',
            field=models.CharField(max_length=15),
        ),
    ]
