# Generated by Django 3.0.3 on 2020-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_xml_search', '0002_auto_20200601_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='charset',
            field=models.CharField(max_length=16),
        ),
    ]
