# Generated by Django 3.0.3 on 2020-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_xml_search', '0003_auto_20200601_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='saved_copy_url',
            field=models.URLField(max_length=300),
        ),
    ]
