# Generated by Django 3.0.3 on 2020-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_xml_search', '0004_auto_20200601_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='saved_copy_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='doc',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
