# Generated by Django 3.0.3 on 2020-10-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unify_context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitadAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unify_context.Action')),
                ('click_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('website_name', models.CharField(max_length=50)),
            ],
            bases=('unify_context.action',),
        ),
        migrations.CreateModel(
            name='AdmitadProgram',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unify_context.Program')),
                ('site_url', models.URLField()),
                ('rating', models.FloatField()),
                ('ecpc', models.IntegerField()),
                ('cr', models.FloatField()),
                ('rate_of_approve', models.FloatField()),
                ('goto_cookie_lifetime', models.IntegerField()),
                ('avg_money_transfer_time', models.IntegerField()),
                ('avg_hold_time', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
            ],
            bases=('unify_context.program',),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gotolink', models.URLField()),
                ('products_xml_link', models.URLField()),
                ('advcampaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admitad_manager.AdmitadProgram')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admitad_manager.Website')),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='program_set',
            field=models.ManyToManyField(through='admitad_manager.WebsiteProgram', to='admitad_manager.AdmitadProgram'),
        ),
    ]
