# Generated by Django 3.0.3 on 2020-10-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admitad_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteprogram',
            old_name='advcampaign',
            new_name='program',
        ),
    ]
