# Generated by Django 3.0.3 on 2020-10-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admitad_manager', '0002_auto_20201003_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitadprogram',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='admitadprogram',
            name='ecpc',
        ),
        migrations.RemoveField(
            model_name='admitadprogram',
            name='rate_of_approve',
        ),
    ]
