# Generated by Django 3.0.3 on 2020-10-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unify_context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCakeAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unify_context.Action')),
            ],
            bases=('unify_context.action',),
        ),
        migrations.CreateModel(
            name='AdvCakeProgram',
            fields=[
                ('program_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='unify_context.Program')),
            ],
            bases=('unify_context.program',),
        ),
    ]
